essay/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('main.urls')),
]

main/urls.py
from django.urls import path  # , include
from . import views
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetCompleteView, PasswordResetConfirmView


app_name = 'main'
urlpatterns = [
    path('', views.HomePageView.as_view(), name='homepage'),

    path('tasks', views.TasksView.as_view(), name='tasks'),
    path('tasks/<int:task_id>/', views.ith_task, name='ith_task'),
    path('tasks/<int:task_id>/submit', views.submit_essay, name='submit_essay'),

    path(r'signup/', views.signup_redirect, name='signup'),
    path(r'signup/redirect', views.signup_redirect, name='signup_redirect'),

    path(r'^login/$', LoginView.as_view(), name='login'),
    path(r'^logout/$', LogoutView.as_view(), name='logout'),

    path(r'^reset-password/$', PasswordResetView.as_view(), name='password_reset'),
    path(r'^reset-password/done/$', PasswordResetDoneView.as_view(), name='password_reset_done'),
    path(r'^reset-password/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$', PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path(r'^reset-password/complete/$', PasswordResetCompleteView.as_view(), name='password_reset_complete'),

    # Profile
    path('me', views.me, name='me'),
    path('me/edit', views.me_edit, name='me_edit'),

    # Essays
    path('me/essays', views.my_essays, name='my_essays'),
    path('me/essays/<int:essay_id>', views.my_ith_essay, name='my_ith_essay'),
    path('me/essays/<int:essay_id>/update', views.update_essay, name='update_essay'),
    path('me/essays/<int:essay_id>/delete', views.delete_essay, name='delete_essay'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User


class TaskCategory(models.Model):
    name = models.CharField(max_length=100)
    image_url = models.TextField()

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name


class Task(models.Model):
    title = models.TextField()
    created_date = models.DateField(auto_now=False, auto_now_add=True)
    last_modified = models.DateField(auto_now=True)
    category = models.ForeignKey(TaskCategory, on_delete=models.SET_NULL, blank=True, null=True)

    def __str__(self):
        return self.title[:100]


class Essay(models.Model):
    created_date = models.DateField(auto_now=False, auto_now_add=True)
    last_modified = models.DateField(auto_now=True)
    task = models.ForeignKey(Task, on_delete=models.SET_DEFAULT, blank=False, default='The task for this essays is not set or was deleted')
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank=False)
    text = models.TextField()

    def __str__(self):
        return f"{self.text[:100]}"

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    email = forms.CharField(max_length=50, required=True, help_text='Required.')

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2', )

main/views.py
from django.http import HttpResponseRedirect  # HttpResponse,
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Task, Essay
from django.contrib.auth.models import User
from .forms import SignUpForm

from django.views import generic


class HomePageView(generic.ListView):
    template_name = "main/index.html"
    context_object_name = "task_count"

    def get_queryset(self):
        """Return number of Tasks."""
        return Task.objects.all().count()


class TasksView(generic.ListView):
    context_object_name = "task_list"
    model = Task


# class TaskDetailView(generic.DetailView):
    # context_object_name = "task"
    # model = Task

@login_required
def ith_task(request, task_id):
    query_set = get_object_or_404(Task, pk=task_id)
    # TODO: test cases when 404 is returned
    context = {
        "task": query_set,
    }
    return render(request, "main/essay_write_form.html", context)


@login_required
def submit_essay(request, task_id):
    task = get_object_or_404(Task, pk=task_id)
    answer = request.POST["essay"]
    if len(answer) == 0:
        return render(request, "main/essay_write_form.html", {
            "task": task,
            "error_msg": "You did not provide answer.",
        })
    else:
        Essay.objects.create(task=task, user=request.user, text=answer)
        return HttpResponseRedirect(reverse('main:my_essays'))


@login_required
def update_essay(request, essay_id):
    # task = get_object_or_404(Task, pk=task_id)
    answer = request.POST["essay"]
    if len(answer) == 0:
        # TODO: change this to the view_my_essay.html and corresponding context
        return render(request, "main/essay_write_form.html", {
            "error_msg": "You did not provide answer.",
        })
    else:
        essay = Essay.objects.get(id=essay_id, user=request.user.id)
        if essay is not None:
            essay.text = answer
            essay.save()
        else:
            Essay.objects.create(task=essay.task, user=request.user, text=answer)
        return HttpResponseRedirect(reverse('main:my_essays'))


@login_required
def delete_essay(request, essay_id):
    essay = Essay.objects.get(pk=essay_id)
    if essay is not None:
        essay.delete()
    return HttpResponseRedirect(reverse('main:my_essays'))


def signup_redirect(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        context = {}
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('main:login'))
        else:
            # print(form.errors.as_data())
            context = {
                'form': form,
            }
    else:
        context = {
            'form': SignUpForm()
        }
    return render(request, "main/registration/signup.html", context)


@login_required
def me(request):
    user = get_object_or_404(User, pk=request.user.id)
    essay_number = len(Essay.objects.filter(user_id=user.id))
    context = {
        "user": user,
        "essay_number": essay_number,
    }
    return render(request, "main/me.html", context)


@login_required
def me_edit(request):
    user = get_object_or_404(User, pk=request.user.id)

    username = request.POST["username"]
    email = request.POST["email"]
    password = request.POST["new_password"]
    confirm_password = request.POST["confirm_password"]

    # check that password == confirm_password
    if password == confirm_password:
        user.username = username
        user.email = email
        user.password = password
        user.save()
        return HttpResponseRedirect(reverse('main:me'))
    else:
        context = {
            "error_msg": "Passwords do not match",
        }
        return render(request, "main/me.html", context)


@login_required
def my_essays(request):
    query_set = Essay.objects.filter(user_id=request.user.id)
    if len(query_set) != 0:
        context = {
            "essay_list": query_set,
        }
    else:
        context = {}

    return render(request, "main/my_essays.html", context)


# TODO: allow essay editting
@login_required
def my_ith_essay(request, essay_id):
    essay = Essay.objects.filter(user_id=request.user.id, id=essay_id)
    if essay.exists():
        context = {
            "essay": essay[0],
        }
        return render(request, "main/view_my_essay.html", context)
    else:
        context = {
            "error": "essay does not exist",
        }
        return render(request, "main/view_my_essay.html", context)

main/templates/main/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Essy</title>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Indie+Flower&family=Lato&display=swap" rel="stylesheet">
    
    {% block css %}
    {% endblock %}

    <link href="{% static 'css/footer.css' %}" rel="stylesheet">
  </head>
  <body>
    {% include 'main/navbar.html' %}
   
          {% block content %}
          {% endblock %}
    {% include 'main/footer.html' %}
  </body>
</html>

main/templates/main/essay_write_form.html
{% extends 'main/base.html' %}

{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/write_view_essay.css' %}">
{% endblock %}


{% block content %}
    
    {% if error_msg %}
      <p><strong>{{ error_msg }}</strong></p>
    {% else %}

    <div class="write-view-edit-page-div">   
      <textarea readonly class="task-textarea">
You should spend about 40 minutes on this task.
Write about the following topic.


{{ task.title }}


You should write at least 250 words.
      </textarea>
  
          
      
      <form action="{% url 'main:submit_essay' task.id %}" method="post">
        <div id="control-n-stats">
          <ul class="horizontal-list">
            <li><p id="wordCount">Words: 0</p></li>
            <li><p id="timer">Time: 0</p></li>
            <li><input type="submit" class="btn btn-success" value="Submit"></li>
          </ul>
        </div>
      <hr class="mt-0 mb-4">
        {% csrf_token %}

        <textarea name="essay" id="input" class="write-textarea" rows='7' placeholder='Write your Answer Here' data-min-rows='7'></textarea>


      </form>

      <script src="{% static 'js/textarea_script.js' %}"></script>
      <script src="{% static 'js/word_counter.js' %}"></script>
  </div>
  {% endif %}

    
{% endblock %}

main/templates/main/footer.html
<div class="footer">
    <div class="container">
        <div class="row ">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 ">
                <div class="ft-logo"><!-- <img src="https://easetemplate.com/free-website-templates/cointrade/images/logo.png" alt=""> -->Essy</div>
            </div>
        </div>
        <hr class="footer-line">
        <div class="row ">
            <!-- footer-about -->
            <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6 col-6 ">
                <div class="footer-widget ">
                    <div class="footer-title">Website</div>
                    <ul class="list-unstyled">
                        <li><a href="#">About</a></li>
                        <li><a href="#">Support</a></li>
                        <!-- <li><a href="#">Press</a></li> -->
                        <!-- <li><a href="#">Legal & Privacy</a></li> -->
                    </ul>
                </div>
            </div>
            <!-- /.footer-about -->
            <!-- footer-links -->
            <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6 col-6 ">
                <div class="footer-widget ">
                    <div class="footer-title">Quick Links</div>
                    <ul class="list-unstyled">
                        <!-- <li><a href="#">News</a></li> -->
                        <li><a href="#">Contact us</a></li>
                        <li><a href="#">FAQ</a></li>
                    </ul>
                </div>
            </div>
            <!-- /.footer-links -->
            <!-- footer-links -->
            <div class="col-xl-3 col-lg-3 col-md-4 col-sm-6 col-6 ">
                <div class="footer-widget ">
                    <div class="footer-title">Social</div>
                    <ul class="list-unstyled">
                        <li><a href="#">VK</a></li>
                        <!-- <li><a href="#">Google +</a></li> -->
                        <!-- <li><a href="#">Linked In</a></li> -->
                        <!-- <li><a href="#">Facebook</a></li> -->
                    </ul>
                </div>
            </div>
            <!-- /.footer-links -->
            <!-- footer-links -->
            <!-- <div class="col-xl-3 col-lg-3 col-md-12 col-sm-6 col-6 ">
                <div class="footer-widget ">
                    <h3 class="footer-title">Subscribe Newsletter</h3>
                    <form>
                        <div class="newsletter-form">
                            <input class="form-control" placeholder="Enter Your Email address" type="text">
                            <button class="btn btn-default btn-sm" type="submit">Go</button>
                        </div>
                    </form>
                </div>
            </div> -->
            <!-- /.footer-links -->
            <!-- tiny-footer -->
        </div>
        
        <div class="row ">
            <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12 text-center ">
                <div class="tiny-footer">
                    <p>Copyright © All Rights Reserved 2020</p>
                </div>
            </div>
            <!-- /. tiny-footer -->
        </div>
    </div>
</div>

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

<!-- justify-content-center -->
{% block content %}

<div class="container-fluid">
  <div class="row">   
    <div class="col-md-5" id="region1-left_div">
        <br>
        <h1 id="welcome-text"><i>Welcome, this is Essy</i></h1>
<pre>

Here you can write essays to
More than 1000 essay questions

All your essays will be stored
You can change them later
Share via social networks
And Many Many More...

<a id="random_link" href="{% url 'main:ith_task' task_id=1 %}">Answer to Random Task</a>
</pre> 
    </div>


    <div class="col-md-7">
        <img class="region1-image" src="https://images.unsplash.com/photo-1518674660708-0e2c0473e68e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format">
    </div>

  </div>
</div>
    <!-- Make random among valid task numbers -->
    <script>
    function getRandomInt(max) {
      return Math.floor(Math.random() * Math.floor(max));
    }
    var rand = 1 + getRandomInt( {{task_count}} );
    var url_mask = "{% url 'main:ith_task' task_id=1 %}".replace(/1/, rand.toString());

    document.getElementById("random_link").href = url_mask;
    </script>

{% endblock %}

main/templates/main/me.html
{% extends 'main/base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/profile.css' %}">
{% endblock %}

{% block content %}

<div class="wrapper">
  <section class="section-pic parallax parallax-text bg1">
     <h2><strong>{{ user.first_name}} {{ user.last_name }}</strong></h2>
     <h4 class="username-text">@{{ user.username }}</h4>
     
     <h5><a class="essay-count-text" href="{% url 'main:my_essays' %}"> {{ essay_number }} essay(s)</a></h5>
     <!-- <h3>Last Login: {{ user.last_login }}</h3> -->
     <!-- <h3>Registration Date: {{ user.date_joined }}</h3> -->
  </section>
  <section class="section static bio-text">
    <h4>About Me:</h4>
    <h6>Here should be some text about the person. This text will be retrieved from User's account where will be a new field bio. User can change that bio but for now this field will contain temporary message.</h6>
  </section>
</div>
{% endblock %}





 <!-- <section class="section parallax bg2"> -->
    
  <!-- <div class="card" style="width: 30rem;">
    <div class="card-body">
      <h5 class="card-title">Edit Profile</h5>
      <form method="post" action="{% url 'main:me_edit' %}">
        {% csrf_token %}
        <table>
          <tr>
            <td>User Name</td>
            <td><input name="username" type="text"/></td>
          </tr>
          <tr>
            <td>Email</td>
            <td><input name="email" type="text"/></td>
          </tr>
          <tr>
            <td>Current Password</td>
            <td><input name="current_password" type="text"/></td>
          </tr>
          <tr>
            <td>New Password</td>
            <td><input name="new_password" type="text"/></td>
          </tr>
          <tr>
            <td>Confirm Password</td>
            <td><input name="confirm_password" type="text"/></td>
          </tr>
        </table>
        <input type="submit" value="Save" />
        
      </form>
    </div>
  </div> -->
    
  <!-- </section> -->

main/templates/main/my_essays.html
{% extends 'main/base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/card.css' %}">
{% endblock %}

{% block content %}

{% if essay_list %}
    <div class="container mt-4">
        <div class="row">
            {% for essay in essay_list %}        
                <div class="col-auto bg-light mb-3">
                    <div class="card" style="width: 15rem;">
                        <img src="{{ essay.task.category.image_url}}" class="card-img-top card-image" alt="Image not found">
                        <div class="card-header">{{ essay.task.category }}: {{ essay.last_modified }}</div>
                        <div class="card-body">
                            <p class="card-text"></p>
                            <p class="card-text">{{ essay }}</p>
                            <a href="{% url 'main:my_ith_essay' essay.id %}" class="card-link">View Essay</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% else %}
    <div id="no-objects-card">
        <h3>You don't have essays</h3>
        <a role="button" class="btn btn-primary" id="write-essay-btn" href="{% url 'main:tasks' %}">Write Essay</a>
    </div>
{% endif %}

{% endblock %}

main/templates/main/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" id="navbar-website-name" href="{% url 'main:homepage' %}">Essy</a>
    
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    
    <span class="navbar-toggler-icon"></span>
  </button>     

    <div class="collapse navbar-collapse"  id="navbarNavDropdown">
      <ul class="nav navbar-nav">
        
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'main:tasks' %}">Tasks</a>
        </li>

        {% if user.is_authenticated %}        
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'main:my_essays' %}">My Essays</a>
          </li>         
          
        </ul>

        <div class="navbar-collapse collapse">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'main:me' %}">{{ user}}</a>
              </li>
        
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'main:logout' %}">Log Out</a>
              </li>
            </ul>
        </div>

        {% else %}
        <ul class="nav navbar-nav navbar-right">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'main:login' %}">Log in</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'main:signup' %}">Sign up</a>
          </li>
        </ul>
        {% endif %}
      
    </div>
</nav>

main/templates/main/task_list.html
{% extends 'main/base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/card.css' %}">
{% endblock %}

{% block content %}

<div class="container mt-4">
    <div class="row">
        {% for task in task_list %}        
        <div class="col-auto bg-light mb-3">
            <div class="card" style="width: 15rem;">
                <img src="{{ task.category.image_url }}" class="card-img-top card-image" alt="Image not found">
                <div class="card-header">{{ task.category }}</div>
                <div class="card-body">
                    <p class="card-text">{{ task }}</p>
                    <a href="{% url 'main:ith_task' task.id %}" class="card-link">Write Essay</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

main/templates/main/tasks.html
{% extends 'main/base.html' %}
{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/card.css' %}">
{% endblock %}

{% block content %}

<div class="container mt-4">
    <div class="row">
        {% for task in task_list %}        
        <div class="col-auto bg-light mb-3">
            <div class="card" style="width: 15rem;">
                <img src="{{ task.category.image_url }}" class="card-img-top card-image" alt="Image not found">
                <div class="card-header">{{ task.category }}</div>
                <div class="card-body">
                    <p class="card-text">{{ task }}</p>
                    <a href="{% url 'main:ith_task' task.id %}" class="card-link">Write Essay</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

main/templates/main/view_my_essay.html
{% extends 'main/base.html' %}

{% load static %}
{% block css %}
    <link rel="stylesheet" href="{% static 'css/write_view_essay.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

{% block content %}    
    {% if error %}
        <h3>{{ error }}</h3>
    {% else %}
    <div class="write-view-edit-page-div">   
        <textarea readonly class="task-textarea">{{ essay.task.title }}</textarea>
        <br>
        <form action="{% url 'main:update_essay' essay.id %}" method="post">
        
        <div id="control-n-stats">
          <ul class="horizontal-list">
            <li><p id="wordCount">Words: 0</p></li>
            <!-- <li><p id="">Time: 0</p></li> -->
            <li><input type="button" class="btn btn-success" id="edit-essay-btn" value="Edit the Essay"></li>
            <li><input type="button" class="btn btn-success" id="cross-btn" value="X"></li>
            <li><input type="submit" class="btn btn-success" id="submit-btn" value="Submit"></li>
          </ul>
        </div>
        <hr class="mt-0 mb-4">

            {% csrf_token %}
            <textarea readonly name="essay" rows='9' id='input' data-min-rows='9' class='write-textarea'>{{ essay.text }}</textarea>
        </form>
    
        <hr class="mt-0 mb-4">    
        <form action="{% url 'main:delete_essay' essay.id %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn"><i class="fa fa-trash"></i> Delete</button>
        </form>
        <script src="{% static 'js/word_counter.js' %}"></script>
        <script src="{% static 'js/edit_essay.js' %}"></script>
    </div>
    <br>
    {% endif %}
{% endblock %}